### ISSUE TITLE
Error: Could not generate GraphQL type definitions (web) on Redwood 7.4

### ISSUE THREAD

**Issue by senpo** [chrisvdm/redwoodjs-stripe#138]
I used the quick start command to bootstrap.
`$ npx @redwoodjs-stripe/cli@latest setup`

`$ yarn rw generate types` and `$ yarn rw dev` will yield the same error:
```
... done with errors.

Error: Could not generate GraphQL type definitions (web)

Error: GraphQL Document Validation failed with 2 errors;
  Error 0: Unknown type "StripeItemsParamsInput".
    at web/src/components/StripeItemsCell/StripeItemsCell.tsx:1:28

Error 1: Cannot query field "stripeItems" on type "Query".
    at web/src/components/StripeItemsCell/StripeItemsCell.tsx:2:3
    at codegen (node_modules/@graphql-codegen/core/cjs/codegen.js:83:19)
    ..........
```

**Comment by chrisvdm** [comment]
@senpo Thank you for bringing it up. I know about this. It just shows up when starting up but it shouldn't affect the app. Regardless, I'll look into a way to fix this, I understand it definitely does look something broke.
